theme = {
    "area": {"fill": "#30a2da"},
    "axis": {
        "domainColor": "#cbcbcb",
        "grid": True,
        "gridColor": "#cbcbcb",
        "gridWidth": 1,
        "labelFont":"Lato",
        "labelColor": "#222",
        "labelFontSize": 10,
        "titleColor": "#666",
        "tickColor": "#7d7c7c",
        "tickSize": 14,
        "titleFont":"Lato",
        "titleFontSize": 12,
        "titlePadding": 10,
        "labelPadding": 4,
    },
    "axisBand": {"grid": False},
    "legend": {
        "orient":"right",
        "direction":"vertical",
        "offset":28,
        "labelFont":"Lato",
        "labelColor": "#333",
        "labelFontSize": 12,
        "padding": 1,
        "symbolSize": 100,
        "symbolType": "square",
        "titleColor": "#333",
        "titleFont":"Lato",
        "titleFontSize": 14,
        "titlePadding": 10,
    },
    "line": {"stroke": "#9651b1", "strokeWidth": 2},
    "rect": {"fill": "#36e7f4"},
    "range": {
        "category": [
            "#FFCC33",
            "#B2B4AE",
            "#1C5687",
            "#85458A",
            "#4C7D7A",
            "#30a2da",
            "#3aab67",
            "#8a512a",
            "#e5ae38",
            "#6d904f",
            "#8b8b8b",
            "#b96db8",
            "#ff9e27",
            "#56cc60",
            "#fc4f30",
            "#36f443",
            "#52d2ca",
            "#52689e",
            "#545454",
            "#9fe4f8",
        ],
        #"diverging": ["#cc0020", "#e77866", "#f6e7e1", "#d6e8ed", "#91bfd9", "#1d78b5"],
        "diverging": ["#FFCC33","#B2B4AE", "#85458A", "#1C5687", "#F44336", "#ef3c79", "#3aab67"],
        "heatmap": ["#FFCC33","#B2B4AE", "#85458A", "#1C5687","#549cc6", "#1d78b5"],
    },
    "point": {"filled": True, "shape": "circle"},
    "bar": {"binSpacing": 2, "fill": "#1C5687", "stroke": None},
    "title": {"anchor": "start","font":"Lato", "fontSize": 24, "fontWeight": 600, "offset": 20},
    "text": {
                "font": "Lato",
                "color": "#1696d2",
                "fontSize": 11,
                "fontWeight": 400,
                "size": 11,
            },
}